import type { TitleCard, VibeCard } from "@/lib/types";

export const VIBE_CARDS: VibeCard[] = [
  {
    id: "comfort",
    name: "Comfort",
    description: "Cozy, familiar, low-stakes warmth",
    prompt: "comforting cozy feel-good familiar warm",
  },
  {
    id: "funny",
    name: "Funny",
    description: "Comedy, wit, and easy laughs",
    prompt: "funny comedy witty laugh-out-loud humorous",
  },
  {
    id: "intense",
    name: "Intense",
    description: "High stakes, thrill, edge-of-seat",
    prompt: "intense thrilling gripping high-stakes suspense",
  },
  {
    id: "thoughtful",
    name: "Thoughtful",
    description: "Smart, reflective, lingering ideas",
    prompt: "thoughtful cerebral reflective intelligent slow-burn",
  },
  {
    id: "romantic",
    name: "Romantic",
    description: "Love stories and chemistry",
    prompt: "romantic love story chemistry heartfelt",
  },
  {
    id: "scary",
    name: "Scary",
    description: "Horror, dread, jump scares",
    prompt: "scary horror tense frightening creepy",
  },
  {
    id: "feel-good",
    name: "Feel-good",
    description: "Uplifting, hopeful, big heart",
    prompt: "feel-good uplifting hopeful wholesome",
  },
  {
    id: "mind-bending",
    name: "Mind-bending",
    description: "Twists, puzzles, reality slips",
    prompt: "mind-bending twisty sci-fi puzzle surreal",
  },
  {
    id: "epic",
    name: "Epic",
    description: "Scale, spectacle, world-building",
    prompt: "epic spectacular adventure grand world-building",
  },
  {
    id: "cozy-mystery",
    name: "Mystery",
    description: "Clues, secrets, who-did-it",
    prompt: "mystery detective clues secrets investigation",
  },
];

/** Static swipe decks so onboarding works with no API keys. */
export const FALLBACK_MOVIES: TitleCard[] = [
  {
    tmdbId: 693134,
    mediaType: "movie",
    name: "Dune: Part Two",
    year: 2024,
    overview: "Paul Atreides unites with the Fremen to wage war against House Harkonnen.",
    genres: ["Science Fiction", "Adventure"],
    posterPath: "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    backdropPath: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    voteAverage: 8.1,
  },
  {
    tmdbId: 872585,
    mediaType: "movie",
    name: "Oppenheimer",
    year: 2023,
    overview: "The story of J. Robert Oppenheimer and the atomic bomb.",
    genres: ["Drama", "History"],
    posterPath: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropPath: "/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    voteAverage: 8.1,
  },
  {
    tmdbId: 569094,
    mediaType: "movie",
    name: "Spider-Man: Across the Spider-Verse",
    year: 2023,
    overview: "Miles Morales catapults across the Multiverse.",
    genres: ["Animation", "Action", "Adventure"],
    posterPath: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdropPath: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    voteAverage: 8.3,
  },
  {
    tmdbId: 545611,
    mediaType: "movie",
    name: "Everything Everywhere All at Once",
    year: 2022,
    overview: "An exhausted laundromat owner is swept into a chaotic multiverse.",
    genres: ["Action", "Adventure", "Science Fiction"],
    posterPath: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    backdropPath: "/uOzO6BpkCCBSD2UUI38KYPOsxwO.jpg",
    voteAverage: 7.8,
  },
  {
    tmdbId: 414906,
    mediaType: "movie",
    name: "The Batman",
    year: 2022,
    overview: "Batman uncovers corruption in Gotham while pursuing the Riddler.",
    genres: ["Crime", "Mystery", "Action"],
    posterPath: "/74xTEgt7R36FbrdmRih3olXxDBg.jpg",
    backdropPath: "/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    voteAverage: 7.7,
  },
  {
    tmdbId: 496243,
    mediaType: "movie",
    name: "Parasite",
    year: 2019,
    overview: "A poor family schemes to become employed by a wealthy household.",
    genres: ["Comedy", "Thriller", "Drama"],
    posterPath: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdropPath: "/hiKmpZMGZsrkA3cdce8a7Dqlbjy.jpg",
    voteAverage: 8.5,
  },
  {
    tmdbId: 346698,
    mediaType: "movie",
    name: "Barbie",
    year: 2023,
    overview: "Barbie leaves Barbieland for the real world.",
    genres: ["Comedy", "Adventure"],
    posterPath: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    backdropPath: "/ctMserH8g2SeOAnCw5gFJdPf1VD.jpg",
    voteAverage: 7.0,
  },
  {
    tmdbId: 157336,
    mediaType: "movie",
    name: "Interstellar",
    year: 2014,
    overview: "Explorers travel through a wormhole in search of a new home.",
    genres: ["Science Fiction", "Drama", "Adventure"],
    posterPath: "/gEU2QniFS6lPKThQgC4GGhL8D2.jpg",
    backdropPath: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    voteAverage: 8.4,
  },
  {
    tmdbId: 244786,
    mediaType: "movie",
    name: "Whiplash",
    year: 2014,
    overview: "A young drummer enrolls at a cut-throat music conservatory.",
    genres: ["Drama", "Music"],
    posterPath: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdropPath: "/fRGxZuo7jJUWQsVg9ePmZG7ktXv.jpg",
    voteAverage: 8.4,
  },
  {
    tmdbId: 120467,
    mediaType: "movie",
    name: "The Grand Budapest Hotel",
    year: 2014,
    overview: "A legendary concierge and his lobby boy become wrapped in a theft.",
    genres: ["Comedy", "Adventure"],
    posterPath: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdropPath: "/nBj0p9Ag0jUTnHXN3b2eD9hB3Yf.jpg",
    voteAverage: 8.0,
  },
  {
    tmdbId: 76341,
    mediaType: "movie",
    name: "Mad Max: Fury Road",
    year: 2015,
    overview: "In a post-apocalyptic wasteland, Max helps Furiosa flee a tyrant.",
    genres: ["Action", "Adventure", "Science Fiction"],
    posterPath: "/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    backdropPath: "/tbhdm8UJAb4ViCTsulYFL3lxMCd.jpg",
    voteAverage: 7.6,
  },
  {
    tmdbId: 792307,
    mediaType: "movie",
    name: "Poor Things",
    year: 2023,
    overview: "Bella Baxter’s adventures after being brought back to life.",
    genres: ["Science Fiction", "Romance", "Comedy"],
    posterPath: "/kCGlIMHnOm8JPXpjE5XtdgKO7qj.jpg",
    backdropPath: "/bQS43HSLZzMjZKHHtb2skzHlUXm.jpg",
    voteAverage: 7.7,
  },
];

export const FALLBACK_SHOWS: TitleCard[] = [
  {
    tmdbId: 1396,
    mediaType: "tv",
    name: "Breaking Bad",
    year: 2008,
    overview: "A chemistry teacher turns to making meth after a cancer diagnosis.",
    genres: ["Crime", "Drama"],
    posterPath: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdropPath: "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    voteAverage: 8.9,
  },
  {
    tmdbId: 1399,
    mediaType: "tv",
    name: "Game of Thrones",
    year: 2011,
    overview: "Noble families wage war for the Iron Throne.",
    genres: ["Sci-Fi & Fantasy", "Drama", "Action & Adventure"],
    posterPath: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    backdropPath: null,
    voteAverage: 8.4,
  },
  {
    tmdbId: 66732,
    mediaType: "tv",
    name: "Stranger Things",
    year: 2016,
    overview: "Kids in Hawkins uncover government secrets and a parallel world.",
    genres: ["Sci-Fi & Fantasy", "Mystery", "Drama"],
    posterPath: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdropPath: "/56v2KjBlU4XaOv9rVYEQypGROQ.jpg",
    voteAverage: 8.6,
  },
  {
    tmdbId: 2316,
    mediaType: "tv",
    name: "The Office",
    year: 2005,
    overview: "A mockumentary on a group of office workers.",
    genres: ["Comedy"],
    posterPath: "/7DJKHzCYEnqtQtdH1cgfTn7D5qp.jpg",
    backdropPath: "/m3tdSyl11fszKmlL7wqAmlzQQfN.jpg",
    voteAverage: 8.7,
  },
  {
    tmdbId: 76331,
    mediaType: "tv",
    name: "Succession",
    year: 2018,
    overview: "The Roy family fights for control of a global media empire.",
    genres: ["Drama"],
    posterPath: "/7HW47XbkNQ5fiwQFYGWbzTm1TB0.jpg",
    backdropPath: "/4Xzz2e7uXbZLhFgxUsw3QslEMz9.jpg",
    voteAverage: 8.5,
  },
  {
    tmdbId: 100088,
    mediaType: "tv",
    name: "The Last of Us",
    year: 2023,
    overview: "Joel and Ellie cross a post-pandemic United States.",
    genres: ["Drama", "Sci-Fi & Fantasy"],
    posterPath: "/uKvVjOkN6QLgmI2AdjaTZN0je2.jpg",
    backdropPath: "/uDgy6hyPd82im6ZLidk39Vh4fwX.jpg",
    voteAverage: 8.6,
  },
  {
    tmdbId: 95396,
    mediaType: "tv",
    name: "Severance",
    year: 2022,
    overview: "Office workers’ memories are split between work and home.",
    genres: ["Drama", "Mystery", "Sci-Fi & Fantasy"],
    posterPath: "/lFf6LLrQjY0k4N1wVbIOvjBPrqN.jpg",
    backdropPath: "/4G03AzcR9oUEuk2YJ6R5YddNOhD.jpg",
    voteAverage: 8.5,
  },
  {
    tmdbId: 97546,
    mediaType: "tv",
    name: "Ted Lasso",
    year: 2020,
    overview: "An American football coach takes a job with a struggling UK soccer team.",
    genres: ["Comedy", "Drama"],
    posterPath: "/5fhZdwv1E0Xq0nE4KqQvQkD2kHh.jpg",
    backdropPath: "/wXNihLltNtYp5fw2ZgOXtLPqUv1.jpg",
    voteAverage: 8.4,
  },
  {
    tmdbId: 94605,
    mediaType: "tv",
    name: "Arcane",
    year: 2021,
    overview: "Champions of two cities collide in a story of power and sisterhood.",
    genres: ["Animation", "Sci-Fi & Fantasy", "Action & Adventure"],
    posterPath: "/fqldf2t8ztc9aiwn3k6mlX3tvWG.jpg",
    backdropPath: "/q8eejQcg1bAqImEV8hcMNOIOCcv.jpg",
    voteAverage: 8.7,
  },
  {
    tmdbId: 82856,
    mediaType: "tv",
    name: "The Mandalorian",
    year: 2019,
    overview: "A lone bounty hunter in the outer reaches of the galaxy.",
    genres: ["Sci-Fi & Fantasy", "Action & Adventure"],
    posterPath: "/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
    backdropPath: "/o7qi2v4uWQ8bZ1tW3KI0Ztn2epk.jpg",
    voteAverage: 8.5,
  },
  {
    tmdbId: 111803,
    mediaType: "tv",
    name: "The White Lotus",
    year: 2021,
    overview: "Guests and staff at a luxury resort collide over a week’s vacation.",
    genres: ["Comedy", "Drama", "Mystery"],
    posterPath: "/gH5iSss8oBpdw9PjjVwNkVL0nFc.jpg",
    backdropPath: "/dY8yZm5Y8Q2p3aB2k3S0nQvQe5E.jpg",
    voteAverage: 7.9,
  },
  {
    tmdbId: 84958,
    mediaType: "tv",
    name: "Loki",
    year: 2021,
    overview: "The God of Mischief steps out of his brother’s shadow.",
    genres: ["Drama", "Sci-Fi & Fantasy"],
    posterPath: "/kEl2t3OhXc3ZbZSWByWUwSDSJiX.jpg",
    backdropPath: "/q3jHCbvRVlFpjNP7ZkMdKw9d3K8.jpg",
    voteAverage: 8.2,
  },
];
