import type { TitleCard, VibeCard } from "@/lib/types";

export const ONBOARDING_DECK_SIZE = 3;

export function shuffleInPlace<T>(items: T[]) {
  for (let i = items.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [items[i], items[j]] = [items[j], items[i]];
  }
  return items;
}

export function sampleOnboardingDeck<T>(
  items: T[],
  size = ONBOARDING_DECK_SIZE,
  isExcluded?: (item: T) => boolean
) {
  const unseen = isExcluded ? items.filter((item) => !isExcluded(item)) : items;
  const pool = unseen.length >= size ? unseen : items;
  return shuffleInPlace([...pool]).slice(0, Math.min(size, pool.length));
}

export const VIBE_CARDS: VibeCard[] = [
  {
    id: "comfort",
    name: "Comfort",
    description: "Cozy, familiar, low-stakes warmth",
    prompt: "comforting cozy feel-good familiar warm",
    backdropPath: "/6n53UI4mX9QMfe2S0Pgt8mGebY1.jpg",
  },
  {
    id: "funny",
    name: "Funny",
    description: "Comedy, wit, and easy laughs",
    prompt: "funny comedy witty laugh-out-loud humorous",
    backdropPath: "/tbzWgnaqhFwN5mCIiwbgN5oiw0V.jpg",
  },
  {
    id: "intense",
    name: "Intense",
    description: "High stakes, thrill, edge-of-seat",
    prompt: "intense thrilling gripping high-stakes suspense",
    backdropPath: "/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
  },
  {
    id: "thoughtful",
    name: "Thoughtful",
    description: "Smart, reflective, lingering ideas",
    prompt: "thoughtful cerebral reflective intelligent slow-burn",
    backdropPath: "/8MUZz7oPXQftFTslZpRP3CVMOoq.jpg",
  },
  {
    id: "romantic",
    name: "Romantic",
    description: "Love stories and chemistry",
    prompt: "romantic love story chemistry heartfelt",
    backdropPath: "/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg",
  },
  {
    id: "scary",
    name: "Scary",
    description: "Horror, dread, jump scares",
    prompt: "scary horror tense frightening creepy",
    backdropPath: "/gJbTXKNTL6O7r7PzF6ZRkJGBlPp.jpg",
  },
  {
    id: "feel-good",
    name: "Feel-good",
    description: "Uplifting, hopeful, big heart",
    prompt: "feel-good uplifting hopeful wholesome",
    backdropPath: "/rQaHA74pevnGsxcKGaoZVGWe9TC.jpg",
  },
  {
    id: "mind-bending",
    name: "Mind-bending",
    description: "Twists, puzzles, reality slips",
    prompt: "mind-bending twisty sci-fi puzzle surreal",
    backdropPath: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
  },
  {
    id: "epic",
    name: "Epic",
    description: "Scale, spectacle, world-building",
    prompt: "epic spectacular adventure grand world-building",
    backdropPath: "/oiwc338EoBgS4sEI2ixAny4KQKg.jpg",
  },
  {
    id: "cozy-mystery",
    name: "Mystery",
    description: "Clues, secrets, who-did-it",
    prompt: "mystery detective clues secrets investigation",
    backdropPath: "/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg",
  },
];

/** Static swipe decks with current TMDB poster paths when the live API is unavailable. */
export const FALLBACK_MOVIES: TitleCard[] = [
  {
    tmdbId: 693134,
    mediaType: "movie",
    name: "Dune: Part Two",
    year: 2024,
    overview: "Paul Atreides unites with the Fremen to wage war against House Harkonnen.",
    genres: ["Science Fiction", "Adventure"],
    posterPath: "/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg",
    backdropPath: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    voteAverage: 8.1,
  },
  {
    tmdbId: 872585,
    mediaType: "movie",
    name: "Oppenheimer",
    year: 2023,
    overview: "The story of J. Robert Oppenheimer and the atomic bomb.",
    genres: ["Drama", "History"],
    posterPath: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropPath: "/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    voteAverage: 8.1,
  },
  {
    tmdbId: 569094,
    mediaType: "movie",
    name: "Spider-Man: Across the Spider-Verse",
    year: 2023,
    overview: "Miles Morales catapults across the Multiverse.",
    genres: ["Animation", "Action", "Adventure"],
    posterPath: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdropPath: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    voteAverage: 8.3,
  },
  {
    tmdbId: 545611,
    mediaType: "movie",
    name: "Everything Everywhere All at Once",
    year: 2022,
    overview: "An exhausted laundromat owner is swept into a chaotic multiverse.",
    genres: ["Action", "Adventure", "Science Fiction"],
    posterPath: "/u68AjlvlutfEIcpmbYpKcdi09ut.jpg",
    backdropPath: "/uOzO6BpkCCBSD2UUI38KYPOsxwO.jpg",
    voteAverage: 7.8,
  },
  {
    tmdbId: 414906,
    mediaType: "movie",
    name: "The Batman",
    year: 2022,
    overview: "Batman uncovers corruption in Gotham while pursuing the Riddler.",
    genres: ["Crime", "Mystery", "Action"],
    posterPath: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdropPath: "/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    voteAverage: 7.7,
  },
  {
    tmdbId: 496243,
    mediaType: "movie",
    name: "Parasite",
    year: 2019,
    overview: "A poor family schemes to become employed by a wealthy household.",
    genres: ["Comedy", "Thriller", "Drama"],
    posterPath: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdropPath: "/hiKmpZMGZsrkA3cdce8a7Dqlbjy.jpg",
    voteAverage: 8.5,
  },
  {
    tmdbId: 346698,
    mediaType: "movie",
    name: "Barbie",
    year: 2023,
    overview: "Barbie leaves Barbieland for the real world.",
    genres: ["Comedy", "Adventure"],
    posterPath: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    backdropPath: "/ctMserH8g2SeOAnCw5gFJdPf1VD.jpg",
    voteAverage: 7.0,
  },
  {
    tmdbId: 157336,
    mediaType: "movie",
    name: "Interstellar",
    year: 2014,
    overview: "Explorers travel through a wormhole in search of a new home.",
    genres: ["Science Fiction", "Drama", "Adventure"],
    posterPath: "/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
    backdropPath: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    voteAverage: 8.4,
  },
  {
    tmdbId: 244786,
    mediaType: "movie",
    name: "Whiplash",
    year: 2014,
    overview: "A young drummer enrolls at a cut-throat music conservatory.",
    genres: ["Drama", "Music"],
    posterPath: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdropPath: "/fRGxZuo7jJUWQsVg9ePmZG7ktXv.jpg",
    voteAverage: 8.4,
  },
  {
    tmdbId: 120467,
    mediaType: "movie",
    name: "The Grand Budapest Hotel",
    year: 2014,
    overview: "A legendary concierge and his lobby boy become wrapped in a theft.",
    genres: ["Comedy", "Adventure"],
    posterPath: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdropPath: "/nBj0p9Ag0jUTnHXN3b2eD9hB3Yf.jpg",
    voteAverage: 8.0,
  },
  {
    tmdbId: 76341,
    mediaType: "movie",
    name: "Mad Max: Fury Road",
    year: 2015,
    overview: "In a post-apocalyptic wasteland, Max helps Furiosa flee a tyrant.",
    genres: ["Action", "Adventure", "Science Fiction"],
    posterPath: "/ulcAi4dKpAjHwYGS08vNyx9H6I9.jpg",
    backdropPath: "/tbhdm8UJAb4ViCTsulYFL3lxMCd.jpg",
    voteAverage: 7.6,
  },
  {
    tmdbId: 792307,
    mediaType: "movie",
    name: "Poor Things",
    year: 2023,
    overview: "Bella Baxter’s adventures after being brought back to life.",
    genres: ["Science Fiction", "Romance", "Comedy"],
    posterPath: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    backdropPath: "/bQS43HSLZzMjZKHHtb2skzHlUXm.jpg",
    voteAverage: 7.7,
  },
];

export const FALLBACK_SHOWS: TitleCard[] = [
  {
    tmdbId: 1396,
    mediaType: "tv",
    name: "Breaking Bad",
    year: 2008,
    overview: "A chemistry teacher turns to making meth after a cancer diagnosis.",
    genres: ["Crime", "Drama"],
    posterPath: "/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg",
    backdropPath: "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    voteAverage: 8.9,
  },
  {
    tmdbId: 1399,
    mediaType: "tv",
    name: "Game of Thrones",
    year: 2011,
    overview: "Noble families wage war for the Iron Throne.",
    genres: ["Sci-Fi & Fantasy", "Drama", "Action & Adventure"],
    posterPath: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    backdropPath: null,
    voteAverage: 8.4,
  },
  {
    tmdbId: 66732,
    mediaType: "tv",
    name: "Stranger Things",
    year: 2016,
    overview: "Kids in Hawkins uncover government secrets and a parallel world.",
    genres: ["Sci-Fi & Fantasy", "Mystery", "Drama"],
    posterPath: "/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg",
    backdropPath: "/56v2KjBlU4XaOv9rVYEQypGROQ.jpg",
    voteAverage: 8.6,
  },
  {
    tmdbId: 2316,
    mediaType: "tv",
    name: "The Office",
    year: 2005,
    overview: "A mockumentary on a group of office workers.",
    genres: ["Comedy"],
    posterPath: "/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg",
    backdropPath: "/m3tdSyl11fszKmlL7wqAmlzQQfN.jpg",
    voteAverage: 8.7,
  },
  {
    tmdbId: 76331,
    mediaType: "tv",
    name: "Succession",
    year: 2018,
    overview: "The Roy family fights for control of a global media empire.",
    genres: ["Drama"],
    posterPath: "/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg",
    backdropPath: "/4Xzz2e7uXbZLhFgxUsw3QslEMz9.jpg",
    voteAverage: 8.5,
  },
  {
    tmdbId: 100088,
    mediaType: "tv",
    name: "The Last of Us",
    year: 2023,
    overview: "Joel and Ellie cross a post-pandemic United States.",
    genres: ["Drama", "Sci-Fi & Fantasy"],
    posterPath: "/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg",
    backdropPath: "/uDgy6hyPd82im6ZLidk39Vh4fwX.jpg",
    voteAverage: 8.6,
  },
  {
    tmdbId: 95396,
    mediaType: "tv",
    name: "Severance",
    year: 2022,
    overview: "Office workers’ memories are split between work and home.",
    genres: ["Drama", "Mystery", "Sci-Fi & Fantasy"],
    posterPath: "/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg",
    backdropPath: "/4G03AzcR9oUEuk2YJ6R5YddNOhD.jpg",
    voteAverage: 8.5,
  },
  {
    tmdbId: 97546,
    mediaType: "tv",
    name: "Ted Lasso",
    year: 2020,
    overview: "An American football coach takes a job with a struggling UK soccer team.",
    genres: ["Comedy", "Drama"],
    posterPath: "/uRHsiw1wLxPHFXkkv4Ix1s0O6f4.jpg",
    backdropPath: "/wXNihLltNtYp5fw2ZgOXtLPqUv1.jpg",
    voteAverage: 8.4,
  },
  {
    tmdbId: 94605,
    mediaType: "tv",
    name: "Arcane",
    year: 2021,
    overview: "Champions of two cities collide in a story of power and sisterhood.",
    genres: ["Animation", "Sci-Fi & Fantasy", "Action & Adventure"],
    posterPath: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    backdropPath: "/q8eejQcg1bAqImEV8hcMNOIOCcv.jpg",
    voteAverage: 8.7,
  },
  {
    tmdbId: 82856,
    mediaType: "tv",
    name: "The Mandalorian",
    year: 2019,
    overview: "A lone bounty hunter in the outer reaches of the galaxy.",
    genres: ["Sci-Fi & Fantasy", "Action & Adventure"],
    posterPath: "/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    backdropPath: "/o7qi2v4uWQ8bZ1tW3KI0Ztn2epk.jpg",
    voteAverage: 8.5,
  },
  {
    tmdbId: 111803,
    mediaType: "tv",
    name: "The White Lotus",
    year: 2021,
    overview: "Guests and staff at a luxury resort collide over a week’s vacation.",
    genres: ["Comedy", "Drama", "Mystery"],
    posterPath: "/gbSaK9v1CbcYH1ISgbM7XObD2dW.jpg",
    backdropPath: "/dY8yZm5Y8Q2p3aB2k3S0nQvQe5E.jpg",
    voteAverage: 7.9,
  },
  {
    tmdbId: 84958,
    mediaType: "tv",
    name: "Loki",
    year: 2021,
    overview: "The God of Mischief steps out of his brother’s shadow.",
    genres: ["Drama", "Sci-Fi & Fantasy"],
    posterPath: "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
    backdropPath: "/q3jHCbvRVlFpjNP7ZkMdKw9d3K8.jpg",
    voteAverage: 8.2,
  },
];
