export type EraPick = {
  mediaType: "movie" | "tv";
  query: string;
  year?: number;
};

/** TGIF / Friday family sitcoms, 80s–90s household sitcoms, and 1990–present blockbusters. */
export const ERA_PACK: EraPick[] = [
  // --- TGIF and Friday-night family (80s–90s) ---
  { mediaType: "tv", query: "Full House", year: 1987 },
  { mediaType: "tv", query: "Family Matters", year: 1989 },
  { mediaType: "tv", query: "Perfect Strangers", year: 1986 },
  { mediaType: "tv", query: "Just the Ten of Us", year: 1988 },
  { mediaType: "tv", query: "Growing Pains", year: 1985 },
  { mediaType: "tv", query: "Who's the Boss?", year: 1984 },
  { mediaType: "tv", query: "Mr. Belvedere", year: 1985 },
  { mediaType: "tv", query: "Webster", year: 1983 },
  { mediaType: "tv", query: "The Hogan Family", year: 1986 },
  { mediaType: "tv", query: "Dinosaurs", year: 1991 },
  { mediaType: "tv", query: "Step by Step", year: 1991 },
  { mediaType: "tv", query: "Hangin' with Mr. Cooper", year: 1992 },
  { mediaType: "tv", query: "Boy Meets World", year: 1993 },
  { mediaType: "tv", query: "Teen Angel", year: 1997 },
  { mediaType: "tv", query: "Two of a Kind", year: 1998 },
  { mediaType: "tv", query: "You Wish", year: 1997 },
  { mediaType: "tv", query: "Brotherly Love", year: 1995 },
  { mediaType: "tv", query: "Muppets Tonight", year: 1996 },
  { mediaType: "tv", query: "America's Funniest Home Videos", year: 1989 },
  { mediaType: "tv", query: "Family Ties", year: 1982 },
  { mediaType: "tv", query: "ALF", year: 1986 },
  { mediaType: "tv", query: "Head of the Class", year: 1986 },
  { mediaType: "tv", query: "Charles in Charge", year: 1984 },
  { mediaType: "tv", query: "Out of This World", year: 1987 },
  { mediaType: "tv", query: "Small Wonder", year: 1985 },
  { mediaType: "tv", query: "My Two Dads", year: 1987 },
  { mediaType: "tv", query: "Punky Brewster", year: 1984 },
  { mediaType: "tv", query: "Silver Spoons", year: 1982 },
  { mediaType: "tv", query: "Diff'rent Strokes", year: 1978 },
  { mediaType: "tv", query: "The Facts of Life", year: 1979 },
  { mediaType: "tv", query: "Gimme a Break!", year: 1981 },
  { mediaType: "tv", query: "Benson", year: 1979 },
  { mediaType: "tv", query: "Happy Days", year: 1974 },
  { mediaType: "tv", query: "Laverne & Shirley", year: 1976 },
  { mediaType: "tv", query: "Joanie Loves Chachi", year: 1982 },
  { mediaType: "tv", query: "Saved by the Bell", year: 1989 },
  { mediaType: "tv", query: "Saved by the Bell: The College Years", year: 1993 },
  { mediaType: "tv", query: "Clarissa Explains It All", year: 1991 },
  { mediaType: "tv", query: "Kenan & Kel", year: 1996 },
  { mediaType: "tv", query: "Sister, Sister", year: 1994 },
  { mediaType: "tv", query: "Smart Guy", year: 1997 },
  { mediaType: "tv", query: "The Parent 'Hood", year: 1995 },
  { mediaType: "tv", query: "Moesha", year: 1996 },
  { mediaType: "tv", query: "7th Heaven", year: 1996 },
  { mediaType: "tv", query: "The Fresh Prince of Bel-Air", year: 1990 },
  { mediaType: "tv", query: "Home Improvement", year: 1991 },
  { mediaType: "tv", query: "Blossom", year: 1990 },
  { mediaType: "tv", query: "Doogie Howser, M.D.", year: 1989 },
  { mediaType: "tv", query: "The Wonder Years", year: 1988 },
  { mediaType: "tv", query: "The Cosby Show", year: 1984 },
  { mediaType: "tv", query: "A Different World", year: 1987 },
  { mediaType: "tv", query: "The Golden Girls", year: 1985 },
  { mediaType: "tv", query: "Empty Nest", year: 1988 },
  { mediaType: "tv", query: "Roseanne", year: 1988 },
  { mediaType: "tv", query: "Night Court", year: 1984 },
  { mediaType: "tv", query: "Family Matters", year: 1989 },
  { mediaType: "tv", query: "Major Dad", year: 1989 },
  { mediaType: "tv", query: "Coach", year: 1989 },
  { mediaType: "tv", query: "Murphy Brown", year: 1988 },
  { mediaType: "tv", query: "Designing Women", year: 1986 },
  { mediaType: "tv", query: "Kate & Allie", year: 1984 },
  { mediaType: "tv", query: "Newhart", year: 1982 },
  { mediaType: "tv", query: "Wings", year: 1990 },
  { mediaType: "tv", query: "Mad About You", year: 1992 },
  { mediaType: "tv", query: "The Drew Carey Show", year: 1995 },
  { mediaType: "tv", query: "NewsRadio", year: 1995 },
  { mediaType: "tv", query: "3rd Rock from the Sun", year: 1996 },
  { mediaType: "tv", query: "Spin City", year: 1996 },
  { mediaType: "tv", query: "Dharma & Greg", year: 1997 },
  { mediaType: "tv", query: "Just Shoot Me!", year: 1997 },
  { mediaType: "tv", query: "Caroline in the City", year: 1995 },
  { mediaType: "tv", query: "Suddenly Susan", year: 1996 },
  { mediaType: "tv", query: "Cybill", year: 1995 },
  { mediaType: "tv", query: "Grace Under Fire", year: 1993 },
  { mediaType: "tv", query: "Ellen", year: 1994 },
  { mediaType: "tv", query: "The Jeff Foxworthy Show", year: 1995 },
  { mediaType: "tv", query: "Unhappily Ever After", year: 1995 },
  { mediaType: "tv", query: "The Wayans Bros.", year: 1995 },
  { mediaType: "tv", query: "The Jamie Foxx Show", year: 1996 },
  { mediaType: "tv", query: "The Steve Harvey Show", year: 1996 },
  { mediaType: "tv", query: "Living Single", year: 1993 },
  { mediaType: "tv", query: "Martin", year: 1992 },
  { mediaType: "tv", query: "Family Matters", year: 1989 },
  { mediaType: "tv", query: "Hangin' with Mr. Cooper", year: 1992 },
  { mediaType: "tv", query: "Boy Meets World", year: 1993 },
  { mediaType: "tv", query: "Sabrina the Teenage Witch", year: 1996 },
  { mediaType: "tv", query: "Clueless", year: 1996 },
  { mediaType: "tv", query: "Moesha", year: 1996 },
  { mediaType: "tv", query: "Sister Sister", year: 1994 },
  { mediaType: "tv", query: "Even Stevens", year: 2000 },
  { mediaType: "tv", query: "Lizzie McGuire", year: 2001 },
  { mediaType: "tv", query: "That's So Raven", year: 2003 },
  { mediaType: "tv", query: "The Suite Life of Zack & Cody", year: 2005 },
  { mediaType: "tv", query: "Hannah Montana", year: 2006 },
  { mediaType: "tv", query: "Wizards of Waverly Place", year: 2007 },
  { mediaType: "tv", query: "iCarly", year: 2007 },
  { mediaType: "tv", query: "Drake & Josh", year: 2004 },
  { mediaType: "tv", query: "The Adventures of Pete & Pete", year: 1993 },
  { mediaType: "tv", query: "Hey Dude", year: 1989 },
  { mediaType: "tv", query: "Salute Your Shorts", year: 1991 },
  { mediaType: "tv", query: "All That", year: 1994 },
  { mediaType: "tv", query: "Are You Afraid of the Dark?", year: 1990 },
  { mediaType: "tv", query: "Roundhouse", year: 1992 },
  { mediaType: "tv", query: "Amen", year: 1986 },
  { mediaType: "tv", query: "227", year: 1985 },
  { mediaType: "tv", query: "The Jeffersons", year: 1975 },
  { mediaType: "tv", query: "Good Times", year: 1974 },
  { mediaType: "tv", query: "What's Happening!!", year: 1976 },
  { mediaType: "tv", query: "One Day at a Time", year: 1975 },
  { mediaType: "tv", query: "Three's Company", year: 1977 },
  { mediaType: "tv", query: "Taxi", year: 1978 },
  { mediaType: "tv", query: "WKRP in Cincinnati", year: 1978 },
  { mediaType: "tv", query: "Too Close for Comfort", year: 1980 },
  { mediaType: "tv", query: "Bosom Buddies", year: 1980 },
  { mediaType: "tv", query: "Night Court", year: 1984 },
  { mediaType: "tv", query: "It's a Living", year: 1980 },
  { mediaType: "tv", query: "My Sister Sam", year: 1986 },
  { mediaType: "tv", query: "The Wonder Years", year: 1988 },
  { mediaType: "tv", query: "Doogie Howser", year: 1989 },
  { mediaType: "tv", query: "Davis Rules", year: 1991 },
  { mediaType: "tv", query: "Family Matters", year: 1989 },
  { mediaType: "tv", query: "Step by Step", year: 1991 },
  { mediaType: "tv", query: "Hangin with Mr Cooper", year: 1992 },
  { mediaType: "tv", query: "On Our Own", year: 1994 },
  { mediaType: "tv", query: "Meego", year: 1997 },
  { mediaType: "tv", query: "Teen Angel", year: 1997 },
  { mediaType: "tv", query: "Two of a Kind", year: 1998 },
  { mediaType: "tv", query: "Odd Man Out", year: 1999 },
  { mediaType: "tv", query: "The Hughleys", year: 1998 },
  { mediaType: "tv", query: "The Parkers", year: 1999 },
  { mediaType: "tv", query: "My Wife and Kids", year: 2001 },
  { mediaType: "tv", query: "The Bernie Mac Show", year: 2001 },
  { mediaType: "tv", query: "George Lopez", year: 2002 },
  { mediaType: "tv", query: "According to Jim", year: 2001 },
  { mediaType: "tv", query: "8 Simple Rules", year: 2002 },
  { mediaType: "tv", query: "Reba", year: 2001 },
  { mediaType: "tv", query: "Yes, Dear", year: 2000 },
  { mediaType: "tv", query: "Still Standing", year: 2002 },
  { mediaType: "tv", query: "Everybody Hates Chris", year: 2005 },
  { mediaType: "tv", query: "The Middle", year: 2009 },
  { mediaType: "tv", query: "Modern Family", year: 2009 },
  { mediaType: "tv", query: "Black-ish", year: 2014 },
  { mediaType: "tv", query: "The Goldbergs", year: 2013 },
  { mediaType: "tv", query: "Fuller House", year: 2016 },
  { mediaType: "tv", query: "Girl Meets World", year: 2014 },

  // --- Blockbusters 1990–present ---
  { mediaType: "movie", query: "Home Alone", year: 1990 },
  { mediaType: "movie", query: "Home Alone 2: Lost in New York", year: 1992 },
  { mediaType: "movie", query: "Ghost", year: 1990 },
  { mediaType: "movie", query: "Pretty Woman", year: 1990 },
  { mediaType: "movie", query: "Dances with Wolves", year: 1990 },
  { mediaType: "movie", query: "Beauty and the Beast", year: 1991 },
  { mediaType: "movie", query: "Aladdin", year: 1992 },
  { mediaType: "movie", query: "Jurassic Park", year: 1993 },
  { mediaType: "movie", query: "Mrs. Doubtfire", year: 1993 },
  { mediaType: "movie", query: "The Fugitive", year: 1993 },
  { mediaType: "movie", query: "Sleepless in Seattle", year: 1993 },
  { mediaType: "movie", query: "Groundhog Day", year: 1993 },
  { mediaType: "movie", query: "A Few Good Men", year: 1992 },
  { mediaType: "movie", query: "Batman Returns", year: 1992 },
  { mediaType: "movie", query: "Speed", year: 1994 },
  { mediaType: "movie", query: "True Lies", year: 1994 },
  { mediaType: "movie", query: "The Mask", year: 1994 },
  { mediaType: "movie", query: "Dumb and Dumber", year: 1994 },
  { mediaType: "movie", query: "Interview with the Vampire", year: 1994 },
  { mediaType: "movie", query: "The Santa Clause", year: 1994 },
  { mediaType: "movie", query: "Apollo 13", year: 1995 },
  { mediaType: "movie", query: "Braveheart", year: 1995 },
  { mediaType: "movie", query: "Babe", year: 1995 },
  { mediaType: "movie", query: "Clueless", year: 1995 },
  { mediaType: "movie", query: "Jumanji", year: 1995 },
  { mediaType: "movie", query: "GoldenEye", year: 1995 },
  { mediaType: "movie", query: "Independence Day", year: 1996 },
  { mediaType: "movie", query: "Twister", year: 1996 },
  { mediaType: "movie", query: "Mission: Impossible", year: 1996 },
  { mediaType: "movie", query: "The Rock", year: 1996 },
  { mediaType: "movie", query: "Space Jam", year: 1996 },
  { mediaType: "movie", query: "101 Dalmatians", year: 1996 },
  { mediaType: "movie", query: "Jerry Maguire", year: 1996 },
  { mediaType: "movie", query: "The Lost World: Jurassic Park", year: 1997 },
  { mediaType: "movie", query: "Men in Black", year: 1997 },
  { mediaType: "movie", query: "Liar Liar", year: 1997 },
  { mediaType: "movie", query: "Austin Powers: International Man of Mystery", year: 1997 },
  { mediaType: "movie", query: "Good Will Hunting", year: 1997 },
  { mediaType: "movie", query: "As Good as It Gets", year: 1997 },
  { mediaType: "movie", query: "The Truman Show", year: 1998 },
  { mediaType: "movie", query: "Armageddon", year: 1998 },
  { mediaType: "movie", query: "There's Something About Mary", year: 1998 },
  { mediaType: "movie", query: "The Waterboy", year: 1998 },
  { mediaType: "movie", query: "Shakespeare in Love", year: 1998 },
  { mediaType: "movie", query: "A Bug's Life", year: 1998 },
  { mediaType: "movie", query: "The Sixth Sense", year: 1999 },
  { mediaType: "movie", query: "American Beauty", year: 1999 },
  { mediaType: "movie", query: "The Phantom Menace", year: 1999 },
  { mediaType: "movie", query: "Notting Hill", year: 1999 },
  { mediaType: "movie", query: "10 Things I Hate About You", year: 1999 },
  { mediaType: "movie", query: "American Pie", year: 1999 },
  { mediaType: "movie", query: "Big Daddy", year: 1999 },
  { mediaType: "movie", query: "The World Is Not Enough", year: 1999 },
  { mediaType: "movie", query: "Cast Away", year: 2000 },
  { mediaType: "movie", query: "X-Men", year: 2000 },
  { mediaType: "movie", query: "Meet the Parents", year: 2000 },
  { mediaType: "movie", query: "How the Grinch Stole Christmas", year: 2000 },
  { mediaType: "movie", query: "Charlie's Angels", year: 2000 },
  { mediaType: "movie", query: "Remember the Titans", year: 2000 },
  { mediaType: "movie", query: "A Beautiful Mind", year: 2001 },
  { mediaType: "movie", query: "Shrek", year: 2001 },
  { mediaType: "movie", query: "Pearl Harbor", year: 2001 },
  { mediaType: "movie", query: "The Fast and the Furious", year: 2001 },
  { mediaType: "movie", query: "Lara Croft: Tomb Raider", year: 2001 },
  { mediaType: "movie", query: "Ocean's Eleven", year: 2001 },
  { mediaType: "movie", query: "A Walk to Remember", year: 2002 },
  { mediaType: "movie", query: "My Big Fat Greek Wedding", year: 2002 },
  { mediaType: "movie", query: "Signs", year: 2002 },
  { mediaType: "movie", query: "Minority Report", year: 2002 },
  { mediaType: "movie", query: "Catch Me If You Can", year: 2002 },
  { mediaType: "movie", query: "Chicago", year: 2002 },
  { mediaType: "movie", query: "The Bourne Identity", year: 2002 },
  { mediaType: "movie", query: "Die Another Day", year: 2002 },
  { mediaType: "movie", query: "Bruce Almighty", year: 2003 },
  { mediaType: "movie", query: "Elf", year: 2003 },
  { mediaType: "movie", query: "Love Actually", year: 2003 },
  { mediaType: "movie", query: "The Italian Job", year: 2003 },
  { mediaType: "movie", query: "Old School", year: 2003 },
  { mediaType: "movie", query: "School of Rock", year: 2003 },
  { mediaType: "movie", query: "50 First Dates", year: 2004 },
  { mediaType: "movie", query: "The Bourne Supremacy", year: 2004 },
  { mediaType: "movie", query: "National Treasure", year: 2004 },
  { mediaType: "movie", query: "The Day After Tomorrow", year: 2004 },
  { mediaType: "movie", query: "Dodgeball", year: 2004 },
  { mediaType: "movie", query: "Anchorman: The Legend of Ron Burgundy", year: 2004 },
  { mediaType: "movie", query: "Napoleon Dynamite", year: 2004 },
  { mediaType: "movie", query: "Wedding Crashers", year: 2005 },
  { mediaType: "movie", query: "The 40-Year-Old Virgin", year: 2005 },
  { mediaType: "movie", query: "Hitch", year: 2005 },
  { mediaType: "movie", query: "Walk the Line", year: 2005 },
  { mediaType: "movie", query: "King Kong", year: 2005 },
  { mediaType: "movie", query: "The Chronicles of Narnia", year: 2005 },
  { mediaType: "movie", query: "Night at the Museum", year: 2006 },
  { mediaType: "movie", query: "The Devil Wears Prada", year: 2006 },
  { mediaType: "movie", query: "Cars", year: 2006 },
  { mediaType: "movie", query: "Casino Royale", year: 2006 },
  { mediaType: "movie", query: "The Departed", year: 2006 },
  { mediaType: "movie", query: "Borat", year: 2006 },
  { mediaType: "movie", query: "Talladega Nights", year: 2006 },
  { mediaType: "movie", query: "Transformers", year: 2007 },
  { mediaType: "movie", query: "Ratatouille", year: 2007 },
  { mediaType: "movie", query: "Superbad", year: 2007 },
  { mediaType: "movie", query: "Knocked Up", year: 2007 },
  { mediaType: "movie", query: "Juno", year: 2007 },
  { mediaType: "movie", query: "Enchanted", year: 2007 },
  { mediaType: "movie", query: "National Treasure: Book of Secrets", year: 2007 },
  { mediaType: "movie", query: "I Am Legend", year: 2007 },
  { mediaType: "movie", query: "The Bourne Ultimatum", year: 2007 },
  { mediaType: "movie", query: "Iron Man", year: 2008 },
  { mediaType: "movie", query: "WALL-E", year: 2008 },
  { mediaType: "movie", query: "The Dark Knight", year: 2008 },
  { mediaType: "movie", query: "Twilight", year: 2008 },
  { mediaType: "movie", query: "Slumdog Millionaire", year: 2008 },
  { mediaType: "movie", query: "Kung Fu Panda", year: 2008 },
  { mediaType: "movie", query: "Mamma Mia!", year: 2008 },
  { mediaType: "movie", query: "Quantum of Solace", year: 2008 },
  { mediaType: "movie", query: "The Hangover", year: 2009 },
  { mediaType: "movie", query: "Up", year: 2009 },
  { mediaType: "movie", query: "Avatar", year: 2009 },
  { mediaType: "movie", query: "The Blind Side", year: 2009 },
  { mediaType: "movie", query: "Star Trek", year: 2009 },
  { mediaType: "movie", query: "The Proposal", year: 2009 },
  { mediaType: "movie", query: "Inception", year: 2010 },
  { mediaType: "movie", query: "Toy Story 3", year: 2010 },
  { mediaType: "movie", query: "The Social Network", year: 2010 },
  { mediaType: "movie", query: "Despicable Me", year: 2010 },
  { mediaType: "movie", query: "How to Train Your Dragon", year: 2010 },
  { mediaType: "movie", query: "The King's Speech", year: 2010 },
  { mediaType: "movie", query: "Tangled", year: 2010 },
  { mediaType: "movie", query: "The Twilight Saga: Eclipse", year: 2010 },
  { mediaType: "movie", query: "Harry Potter and the Deathly Hallows: Part 2", year: 2011 },
  { mediaType: "movie", query: "The Help", year: 2011 },
  { mediaType: "movie", query: "Bridesmaids", year: 2011 },
  { mediaType: "movie", query: "Rise of the Planet of the Apes", year: 2011 },
  { mediaType: "movie", query: "Mission: Impossible – Ghost Protocol", year: 2011 },
  { mediaType: "movie", query: "The Avengers", year: 2012 },
  { mediaType: "movie", query: "The Hunger Games", year: 2012 },
  { mediaType: "movie", query: "Skyfall", year: 2012 },
  { mediaType: "movie", query: "Ted", year: 2012 },
  { mediaType: "movie", query: "Wreck-It Ralph", year: 2012 },
  { mediaType: "movie", query: "Life of Pi", year: 2012 },
  { mediaType: "movie", query: "The Hunger Games: Catching Fire", year: 2013 },
  { mediaType: "movie", query: "Frozen", year: 2013 },
  { mediaType: "movie", query: "Gravity", year: 2013 },
  { mediaType: "movie", query: "The Wolf of Wall Street", year: 2013 },
  { mediaType: "movie", query: "American Hustle", year: 2013 },
  { mediaType: "movie", query: "Despicable Me 2", year: 2013 },
  { mediaType: "movie", query: "Guardians of the Galaxy", year: 2014 },
  { mediaType: "movie", query: "The Lego Movie", year: 2014 },
  { mediaType: "movie", query: "Interstellar", year: 2014 },
  { mediaType: "movie", query: "Gone Girl", year: 2014 },
  { mediaType: "movie", query: "The Grand Budapest Hotel", year: 2014 },
  { mediaType: "movie", query: "Whiplash", year: 2014 },
  { mediaType: "movie", query: "Big Hero 6", year: 2014 },
  { mediaType: "movie", query: "Jurassic World", year: 2015 },
  { mediaType: "movie", query: "Inside Out", year: 2015 },
  { mediaType: "movie", query: "Mad Max: Fury Road", year: 2015 },
  { mediaType: "movie", query: "The Martian", year: 2015 },
  { mediaType: "movie", query: "Star Wars: The Force Awakens", year: 2015 },
  { mediaType: "movie", query: "The Revenant", year: 2015 },
  { mediaType: "movie", query: "Deadpool", year: 2016 },
  { mediaType: "movie", query: "Zootopia", year: 2016 },
  { mediaType: "movie", query: "La La Land", year: 2016 },
  { mediaType: "movie", query: "Rogue One", year: 2016 },
  { mediaType: "movie", query: "Moana", year: 2016 },
  { mediaType: "movie", query: "Arrival", year: 2016 },
  { mediaType: "movie", query: "Hidden Figures", year: 2016 },
  { mediaType: "movie", query: "Wonder Woman", year: 2017 },
  { mediaType: "movie", query: "Get Out", year: 2017 },
  { mediaType: "movie", query: "Coco", year: 2017 },
  { mediaType: "movie", query: "Dunkirk", year: 2017 },
  { mediaType: "movie", query: "It", year: 2017 },
  { mediaType: "movie", query: "Blade Runner 2049", year: 2017 },
  { mediaType: "movie", query: "Thor: Ragnarok", year: 2017 },
  { mediaType: "movie", query: "Black Panther", year: 2018 },
  { mediaType: "movie", query: "Avengers: Infinity War", year: 2018 },
  { mediaType: "movie", query: "A Quiet Place", year: 2018 },
  { mediaType: "movie", query: "A Star Is Born", year: 2018 },
  { mediaType: "movie", query: "Bohemian Rhapsody", year: 2018 },
  { mediaType: "movie", query: "Spider-Man: Into the Spider-Verse", year: 2018 },
  { mediaType: "movie", query: "Mission: Impossible – Fallout", year: 2018 },
  { mediaType: "movie", query: "Avengers: Endgame", year: 2019 },
  { mediaType: "movie", query: "Joker", year: 2019 },
  { mediaType: "movie", query: "Frozen II", year: 2019 },
  { mediaType: "movie", query: "Parasite", year: 2019 },
  { mediaType: "movie", query: "Once Upon a Time in Hollywood", year: 2019 },
  { mediaType: "movie", query: "Toy Story 4", year: 2019 },
  { mediaType: "movie", query: "Us", year: 2019 },
  { mediaType: "movie", query: "1917", year: 2019 },
  { mediaType: "movie", query: "Soul", year: 2020 },
  { mediaType: "movie", query: "Promising Young Woman", year: 2020 },
  { mediaType: "movie", query: "The Invisible Man", year: 2020 },
  { mediaType: "movie", query: "Dune", year: 2021 },
  { mediaType: "movie", query: "No Time to Die", year: 2021 },
  { mediaType: "movie", query: "Spider-Man: No Way Home", year: 2021 },
  { mediaType: "movie", query: "Encanto", year: 2021 },
  { mediaType: "movie", query: "The Suicide Squad", year: 2021 },
  { mediaType: "movie", query: "Shang-Chi and the Legend of the Ten Rings", year: 2021 },
  { mediaType: "movie", query: "Top Gun: Maverick", year: 2022 },
  { mediaType: "movie", query: "Everything Everywhere All at Once", year: 2022 },
  { mediaType: "movie", query: "Avatar: The Way of Water", year: 2022 },
  { mediaType: "movie", query: "The Batman", year: 2022 },
  { mediaType: "movie", query: "Elvis", year: 2022 },
  { mediaType: "movie", query: "Nope", year: 2022 },
  { mediaType: "movie", query: "Black Panther: Wakanda Forever", year: 2022 },
  { mediaType: "movie", query: "Barbie", year: 2023 },
  { mediaType: "movie", query: "Oppenheimer", year: 2023 },
  { mediaType: "movie", query: "Spider-Man: Across the Spider-Verse", year: 2023 },
  { mediaType: "movie", query: "The Super Mario Bros. Movie", year: 2023 },
  { mediaType: "movie", query: "Guardians of the Galaxy Vol. 3", year: 2023 },
  { mediaType: "movie", query: "Wonka", year: 2023 },
  { mediaType: "movie", query: "Dune: Part Two", year: 2024 },
  { mediaType: "movie", query: "Wicked", year: 2024 },
  { mediaType: "movie", query: "Inside Out 2", year: 2024 },
  { mediaType: "movie", query: "Deadpool & Wolverine", year: 2024 },
  { mediaType: "movie", query: "Twisters", year: 2024 },
  { mediaType: "movie", query: "Moana 2", year: 2024 },
  { mediaType: "movie", query: "Anora", year: 2024 },
  { mediaType: "movie", query: "A Complete Unknown", year: 2024 },
];
